import { Raleway } from "next/font/google";
import "./globals.css";
import { GridBackgroundDemo } from "./components/GridBackgroundDemo";


const raleway = Raleway({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "900"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.className} relative min-h-screen bg-background text-foreground`}>
        {/* Background Component */}
        <GridBackgroundDemo />

        {/* Main Content */}
        <div className="relative z-10 w-full min-h-screen">{children}</div>
      </body>
    </html>
  );
}




