import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GridBackgroundDemo } from "./components/GridBackgroundDemo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative min-h-screen bg-background text-foreground">
        {/* Background Component */}
        <GridBackgroundDemo />

        {/* Main Content */}
        <div className="relative z-10 w-full min-h-screen">{children}</div>
      </body>
    </html>
  );
}



